main:
  - name: Mesh Map
    identifier: meshmap
    url: https://map.areyoumeshingwith.us
    weight: 80
    params:
      icon:
        header: Florida Mesh Map
        vendor: font-awesome-solid
        name: map-location-dot
  
  - name: Mesh Telemetry
    identifier: mesh-telemetry
    url: https://malla.areyoumeshingwith.us
    weight: 70
    params:
      icon:
        header: Florida Mesh Telemetry
        vendor: font-awesome-solid
        name: gauge