name: Website Release

on:
  push:
    branches:
      - main
  pull_request:
env:
  AWS_GITHUB_OIDC_ROLE: arn:aws:iam::343598423625:role/flmesh-gbl-github-actions
  AWS_GITHUB_ACTIONS_ROLE: arn:aws:iam::225989335976:role/GitHubActionsExecution

permissions:
  id-token: write
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash
  
jobs:
  terraform:
    name: Deploy Terraform Infrastructure as Code
    runs-on: ubuntu-latest
    outputs:
      distribution: ${{ steps.terraform.outputs.DID }}
      bucket: ${{ steps.terraform.outputs.URL }}
      baseurl: ${{ steps.terraform.outputs.BASE }}

    defaults:
      run:
        working-directory: terraform/
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  ${{ env.AWS_GITHUB_OIDC_ROLE }}
        aws-region: us-east-1

    - name: Terraform Format
      id: fmt
      run: terraform fmt -no-color -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -no-color -backend-config="key=${{ github.repository }}/terraform.tfstate"
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Plan
      id: plan
      env:
        TF_VAR_gh_action_role: ${{ env.AWS_GITHUB_ACTIONS_ROLE }}
      run: terraform plan -out .planfile

    - name: Post PR comment
      if: github.event_name == 'pull_request'
      uses: borchero/terraform-plan-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        planfile: .planfile
        working-directory: terraform/

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        TF_VAR_gh_action_role: ${{ env.AWS_GITHUB_ACTIONS_ROLE }}
      run: terraform apply -no-color -auto-approve .planfile

    - name: Output Terraform values
      id: terraform
      run: |
        echo "DID=$(terraform output -raw cloudFrontDistributionID)" >> "$GITHUB_OUTPUT"
        echo "URL=$(terraform output -raw s3Bucket)" >> "$GITHUB_OUTPUT"
        echo "BASE=$(terraform output -raw hostname)" >> "$GITHUB_OUTPUT"

  hugo:
    name: Generate Hugo site
    runs-on: ubuntu-latest
    needs: terraform

    env:
      HUGO_ENV: production
      HUGO_CACHEDIR: /tmp/hugo_cache
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Setup Dart Sass
      run: sudo snap install dart-sass && sudo snap alias dart-sass sass

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - run: npm ci

    - uses: actions/cache@v4
      with:
        path: ${{ env.HUGO_CACHEDIR }}
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-
      
    - name: Hugo Build
      run: hugo build --gc --cleanDestinationDir --enableGitInfo --minify --baseURL https://${{ needs.terraform.outputs.baseurl }}/
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_GITHUB_OIDC_ROLE }}
        aws-region: us-east-1

    - name: Assume IAM Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_GITHUB_ACTIONS_ROLE }}
        role-chaining: true
        aws-region: us-east-1

    - name: Hugo Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: reggionick/s3-deploy@v4
      with:
        folder: public
        dist-id: ${{ needs.terraform.outputs.distribution }}
        bucket: ${{ needs.terraform.outputs.bucket }}
        bucket-region: us-east-1
        delete-removed: true
        cache: 3600
        private: true
        files-to-include: '{.*/**,**}'
